### PR TITLE
feat: add prop to allow slider position to follow mouse on hover

### PR DESCRIPTION
**Pull request by jsberlanga**
**Summary**

We want to allow handing position on mouse enter.

👉🏻  No other functionality should have changed.

**Test plan**

https://user-images.githubusercontent.com/32543746/129701375-66d4c915-7f72-4b16-965c-3d2a921ab244.mov

### CODE REVIEW

**Comment by jsberlanga** [comment]
@nerdyman could you please take a look at this? 🙏🏻 

I'd love to use your library but we need the on mouse enter feature to be available.

Please let me know wdyt? Many thanks!

**Comment by nerdyman** [comment]
Hey @jsberlanga,

Thanks for opening the PR, this is an awesome feature! I'll review it tonight then hopefully we can get in a release this week.

**Review by nerdyman — CHANGES_REQUESTED** [review]
Thanks for the PR @jsberlanga! I've requested a few changes, let me know if you have any questions or think the feature could be added another way.

Also apologies if the comments are a bit excessive, I really want to keep the library as consistent and flexible as possible so think it's cleaner to make the hover events use the same binding technique as the existing mouse events.

**Comment by jsberlanga** [comment]
thanks so much @nerdyman for your help and suggestions. I've applied your suggested changes and tested that the current functionality keeps working the same way.

**Comment by nerdyman** [comment]
Awesome, thanks for your work @jsberlanga! I've got a few things going on atm so can't do a release tonight but should be able to do one this weekend.

**Comment by nerdyman** [comment]
@jsberlanga this has been published in version [`2.1.0`](https://www.npmjs.com/package/react-compare-slider/v/2.1.0) :rocket:

**Pull request merged**
