### PR TITLE
Next release

### LINKED ISSUE #134: Scroll issue on mobile devices after "touch-action: none" styling
Hello everyone, I wanted to bring to your attention an issue that arose in one of the commits early in 2023 ([Commit Link](https://github.com/nerdyman/react-compare-slider/commit/87ba39ee9258eaaf1ff3b8483f38f03db9c7c83a)).

In this commit, the widget received the style property "touch-action: none", resulting in the disruption of scrolling on relevant devices. This has become a critical issue, especially on mobile phones, where the widget might occupy a significant portion of the screen.

### LINKED ISSUE #144: Jest `Cannot find module 'react-compare-slider' (v3.X)
Running version 3.X of the package is working fine in Storybook etc, however when we come to write tests for our component, we get the following error:

```
Test suite failed to run

Cannot find module 'react-compare-slider' from 'components/BeforeAfter/BeforeAfter.test.tsx'
```

**Reproduction**
The component

```typescript
// components/BeforeAfter/index.tsx

import classNames from "classnames/bind";
import { useTranslation } from "next-i18next";
import { ReactCompareSlider } from "react-compare-slider";
import Icon, { IconName } from "@/components/Icon";
import breakpoints from "@/constants/breakpoints";
import CustomImage from "../CustomImage";
import styles from "./BeforeAfter.module.scss";

const cx = classNames.bind(styles);

export type BeforeAfterProps = {
  /**
   * The title text. Required.
   */
  title: string;
  /**
   * Optional body copy.
   */
  body?: string;
  /**
   * Optional boolean prop to show/hide the divider. Defaults to false.
   */
  divider?: boolean;
  /**
   * Image to use for the 'before' view.
   */
  beforeImage: { altText: string; src: string };
  /**
   * Image to use for the 'after' view.
   */
  afterImage: { altText: string; src: string };
};

const BeforeAfter = ({
  title,
  body,
  divider = false,
  beforeImage,
  afterImage,
}: BeforeAfterProps) => {
  const { t } = useTranslation("common");

  const imageOne = (
    <div className={cx("imageWrap")}>
      <CustomImage
        alt={beforeImage.altText}
        src={`${beforeImage.src}?io=transform:fit`}
        fill
        sizes={`(max-width: ${breakpoints.s}px) 100vw, (max-width: ${breakpoints.oversize}px) 50vw, 960px`} // TODO
      />
    </div>
  );

  const imageTwo = (
    <div className={cx("imageWrap")}>
      <CustomImage
        alt={afterImage.altText}
        src={`${afterImage.src}?io=transform:fit`}
        fill
        sizes={`(max-width: ${breakpoints.s}px) 100vw, (max-width: ${breakpoints.oversize}px) 50vw, 960px`} // TODO
      />
    </div>
  );

  const CustomHandle: React.FC = () => {
    return (
      <div className={cx("customHandle")}>
        <div className={cx("line")}></div>
        <div className={cx("handle")}>
          <Icon name={IconName.DOUBLE_CHEVRON} />
        </div>
        <div className={cx("line")}></div>
      </div>
    );
  };

  return (
    <section className="u-sectionPadding-h">
      <div className={cx("contentWrap", divider && "divider")}>
        <div className={cx("textWrap")}>
          <h4 className={cx("title", "u-strong")}>{title}</h4>
          {body && <p className={cx("body")}>{body}</p>}
        </div>
        <div className={cx("compareImagesWrap")}>
          <ReactCompareSlider
            itemOne={imageOne}
            itemTwo={imageTwo}
            handle={<CustomHandle />}
          />

          <div className={cx("labels")}>
            <h5 className="h6 u-strong">{t("before-after.before")}</h5>
            <h5 className="h6 u-strong">{t("before-after.after")}</h5>
          </div>
        </div>
      </div>
    </section>
  );
};

export default BeforeAfter;
```

Failing test

```typescript
import { render, screen } from "@testing-library/react";
import BeforeAfter from ".";

jest.mock("next-i18next", () => ({
  useTranslation: () => ({
    t: (key: string) => key,
  }),
}));

describe("BeforeAfter component", () => {
  // Basic render test
  it("renders correctly", () => {
    render(
      <BeforeAfter
        title="Test Title"
        beforeImage={{ altText: "Before Image", src: "before.jpg" }}
        afterImage={{ altText: "After Image", src: "after.jpg" }}
      />,
    );
    expect(screen.getByText("Test Title")).toBeInTheDocument();
    expect(screen.getByText("before-after.before")).toBeInTheDocument();
    expect(screen.getByText("before-after.after")).toBeInTheDocument();
  });
});
```

**Expected Behaviour**
A test using a component that utilises `react-compare-slider` should run without errors, using version 3.X of the library.

**Actual Behaviour**
When running version 3.X (tested `3.1.0` and `3.0.1`), the above error occurs when running a jest test for a component that uses the library.

Downgrading to version `2.2.0` resolves the issue.

### LINKED ISSUE #149: Add pkg.pr.new integration for pull requests
Add GitHub Action to test preview builds without publishing to npm.

https://github.com/stackblitz-labs/pkg.pr.new

### PR DESCRIPTION
**Pull request by nerdyman**
- [x] Closes https://github.com/nerdyman/react-compare-slider/issues/136
- [x] Closes #149 
- [x] Closes #134 
- [x] Closes #144

### CODE REVIEW

**Comment by zoltan-mihalyi** [comment]
Hi! Is this PR still in progress?

Are you planning to implement the three way switch?
https://github.com/nerdyman/react-compare-slider/pull/137#issuecomment-2041400345

**Comment by nerdyman** [comment]
Apologies @zoltan-mihalyi! Yeah still planning on doing the three way switch. I'll take a look this weekend.

**Comment by nerdyman** [comment]
@zoltan-mihalyi This will need a major release since it changes the underlying markup. I also found a few issues with the current clip behaviour. `ContainerClip` uses absolute positioning the slider loses its intrinsic sizing when both items are clipped which isn't ideal. I was looking at replacing the absolute positioning with overlapping grid items in the next release so I can do that as part of this PR.

If you need this feature ASAP I can publish a pre-release version for you to use? Just keep in mind there will be changes in the final v4 release.

**Comment by zoltan-mihalyi** [comment]
Thank you for informing!
Is the problem that you described relevant in the three-way switch or in the version merged to `next` branch too?

Very kind of you, I have a workaround for now, but in the long therm it would be nice to use the upstream version.

**Comment by ty0x2333** [comment]
Is there any new progress? @nerdyman

**Comment by nerdyman** [comment]
@ty0x2333 Yeah I think I figured out the layout issues but I need to do more testing on it before doing a release. I'll aim to get a pre-release on npm this week.

@zoltan-mihalyi Sorry I missed your message, the position issue was just for the three way switch IIRC but that should be resolved with the latest updates 🙏

**Comment by nerdyman** [comment]
You can try out the preview release by running on the following:

```sh
pnpm add https://pkg.pr.new/nerdyman/react-compare-slider@143
yarn add https://pkg.pr.new/nerdyman/react-compare-slider@143
npm i https://pkg.pr.new/nerdyman/react-compare-slider@143
```

The slider also has better intrinsic sizing now, it doesn't automatically apply `width: 100%` anymore. It will adapt to the size of `itemOne` and `itemTwo` instead so you might need to adjust your styles if you were relying on that before.

**Comment by zoltan-mihalyi** [comment]
It looks nice, I can't wait for the release :)

**Pull request merged**
